bankmsdb:
 image: mongo:latest
 restart: always
 container_name: "bankmsdb"
 ports:
  - "27017:27017"
 volumes:
  - ./Document_InfoClient.js:/docker-entrypoint-initdb.d/Document_InfoClient.js:ro
infoclientservice:
 build: .
 dockerfile: Dockerfile
 container_name: infoclientservice
 ports:
  - "8085:8080"
 links:
 - bankmsdb