version: '3.8'

services:
 config-server:
  depends_on:
   - clientdb
  container_name: "config-server"
  image: hyness/spring-cloud-config-server
  ports:
   - "8888:8888"
  environment:
   - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/JhojanGuiller/bank-config-server
   - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*

 clientdb:
  image: mongo:latest
  restart: always
  container_name: "clientdb"
  ports:
   - "27017:27017"
  volumes:
   - ./Document_InfoClient.js:/docker-entrypoint-initdb.d/Document_InfoClient.js:ro

 infoclientservice:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: infoclientservice
  ports:
   - "8085:8080"
  links:
   - clientdb