client-mongo:
 image: mongo:latest
 container_name: "client-mongodb"
 ports:
  - 27017:27017
infoclientservice:
 image: infoclientservice:1.0
 container_name: infoclientservice
 ports:
  - 8085:8080
 links:
 - client-mongo